services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rotary
      POSTGRES_PASSWORD: rotary_dev
      POSTGRES_DB: rotary_nautile
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
